update chrome install

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -41,11 +41,18 @@ jobs:
 
       - name: Install ChromeDriver
         run: |
-          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
-          wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
-          unzip chromedriver_linux64.zip
-          sudo mv chromedriver /usr/local/bin/
-          chmod +x /usr/local/bin/chromedriver
+          CHROME_MAJOR_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
+          DRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROME_MAJOR_VERSION}/chromedriver_linux64.zip"
+          if curl --output /dev/null --silent --head --fail "$DRIVER_URL"; then
+              wget -N "$DRIVER_URL"
+              unzip chromedriver_linux64.zip
+              sudo mv chromedriver /usr/local/bin/
+              chmod +x /usr/local/bin/chromedriver
+          else
+              echo "ChromeDriver version $CHROME_MAJOR_VERSION not found."
+              exit 1
+          fi
+      
       
 
       - name: Set up WebDriver Manager
