change web driver options

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -44,6 +44,23 @@ jobs:
           # WebDriverManager will handle the chromedriver download and setup in the tests
           echo "WebDriverManager will handle the ChromeDriver setup."
 
+      - name: Install xvfb and Chrome
+        run: |
+            sudo apt-get update
+            sudo apt-get install -y google-chrome-stable xvfb
+            google-chrome --version
+
+      - name: Start xvfb
+        run: |
+                export DISPLAY=:99
+                Xvfb :99 -screen 0 1920x1080x24 &
+
+      - name: Debug Xvfb
+        run: |
+                echo "Testing Xvfb..."
+                export DISPLAY=:99
+                xdpyinfo -display :99 || echo "Xvfb failed to start"
+
       - name: Cache Maven dependencies
         uses: actions/cache@v3
         with:
@@ -51,6 +68,7 @@ jobs:
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
+            
 
       - name: Set up JDK 21
         uses: actions/setup-java@v3
@@ -62,20 +80,8 @@ jobs:
         run: |
           export JAVA_HOME=$HOME/.sdkman/candidates/java/21-open
           echo "JAVA_HOME is set to $JAVA_HOME"
-          export PATH=$JAVA_HOME/bin:$PATH  
-
-      - name: Install xvfb and Chrome
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y google-chrome-stable xvfb
-          google-chrome --version
-
-      - name: Start xvfb
-        run: |
-          export DISPLAY=:99
-          Xvfb :99 -screen 0 1920x1080x24 &    
-
-#      - name: Run Maven build
+          export PATH=$JAVA_HOME/bin:$PATH
+      #      - name: Run Maven build
 #        run: |
 #          cd e2e_testing
 #          mvn clean install
@@ -84,4 +90,5 @@ jobs:
         run: |
           cd e2e_testing
           mvn test -e
-
+        env:
+          DISPLAY: :99
